### ISSUE TITLE
If I run few request it's mixed results

### ISSUE THREAD

**Issue by zaletskyi** [wjsc/amp-site-validator#2] opened 2018-12-05 15:33 UTC
Hi Walter,
I have an issue, when run 2 tests(250 links each) in same time. And get mixed results of this 2 sites. Could you help me plz?

Regards,
Michael

**Comment by walterscarano** [comment] 2018-12-07 01:41
Hi Michael!

This module currently has not support for multiple batchs in the same file. The problem is that a pool is created when the module is required and not by user demand.

If you can wait, I can make a new release this weekend with the improvement. And if you want to give it a shot,  feel free to create a pull request.

**Comment by wjsc** [comment] 2018-12-16 15:31
Hi Michael!

I have a new branch with your request. Would you like to test it and give me feedback? 

The branch is`wjsc-patch-1`. You can also see https://github.com/wjsc/amp-site-validator/pull/4

**Comment by zaletskyi** [comment] 2018-12-31 16:43
Hi Walter,
Thank you for your time.
I tested branch `wjsc-patch-1` and get mixed results again.

Thanks,
Michael

**Comment by walterscarano** [comment] 2018-12-31 17:09
Do you create multiple validators? Each validator can handle a batch of urls.

**Comment by zaletskyi** [comment] 2018-12-31 19:30
When I send few API calls(250 links each) to 
```app.post('/amp/sites', function (req, res) {

    function sitesURLs(u){
        res.json(u);
    }
    unirest.post("/amp/get-amp-sites")
            .end(function (res, err) {
                sitesURLs(res.body);
            });

    res.sendStatus(200);

});
```

**Comment by zaletskyi** [comment] 2018-12-31 19:31
When I send few API calls(250 links each) to 
```
app.post('/amp/validate', async (req, res, next) => {

    var urls = req.body.urls.split(/[\r\n]+/);

    const urlGenerator = function* () {
        for(i = 0; i < urls.length; i++) {
            yield urls[i];
        }
    }

    try {
        const results = await validator(urlGenerator, 10);
        res.send({
            pass: results.filter( result => result.status === 'PASS' ).length,
            fail: results.filter( result => result.status !== 'PASS' ).length,
            total: urls.length,
            results: results
        });

    } catch (e) {
        next(e);
    }

});
```

**Comment by walterscarano** [comment] 2018-12-31 20:50
Put this line in the top of the file:
const createValidator = require('amp-site-validator');

And this one before the await:
const validator = createValidator();

**Comment by zaletskyi** [comment] 2019-01-02 14:18
> Put this line in the top of the file:
> const createValidator = require('amp-site-validator');
> 
> And this one before the await:
> const validator = createValidator();

I added it too.

**Comment by zaletskyi** [comment] 2019-01-08 18:35
Tested and get the same result.

**Comment by wjsc** [comment] 2019-01-09 00:12
Hi Michael. 

I just tested it and it works fine. Package v3.0.0 was published. 

I think you have something wrong in your code. I close this issue, and if you publish your code maybe I can help you!

**Closed by wjsc** 2019-01-09 00:12 UTC
